### ISSUE TITLE
slack部屋は作るべき？

### ISSUE THREAD

**Issue by pengin01** [NwHub/mob-pro#1]
専用のslack部屋があったほうがよいか？

**Comment by pengin01** [comment]
全然作ってもいいけど、部屋の展開とか招待とかが面倒な予感

**Comment by miyazoon** [comment]
通話ツールにTeamsを使うなら、チャットもTeamsで良いかもですね！

**Comment by pengin01** [comment]
了解〜
Teamsでやってみて不都合があったら変えましょう！
