### ISSUE TITLE
TypeScriptを使うかどうか？

### ISSUE THREAD

**Issue by pengin01** [NwHub/mob-pro#6]
世間の流れに乗ってTypeScriptを使うか？
- 覚えること多くならない？
- Vueの基本を勉強してからでは？
- TypeScript推奨の企業は増えている

**Comment by miyazoon** [comment]
覚えることは多くなりそうですね。
Vueをメインでやりたいのに、TypeScriptのLintのエラーに苦しめられそう。。
一応、現場で利用しているVueはTypeScript利用しています。

**Comment by pengin01** [comment]
あぁ、悩ましいな、、、

Vue2.xはTypeScriptにちゃんと対応してないんですよねぇ。
だからTypescriptの書き方が無理やりになっちゃっているし、、、、

Vue3.xは対応しているようですけど、Nuxt.jsとかで使えるのは、まだ先だろうし

**Comment by pengin01** [comment]
今回はなしで！
