### ISSUE TITLE
開催頻度をどうするか？

### ISSUE THREAD

**Issue by miyazoon** [NwHub/mob-pro#7]
- 週一？隔週？月一？など
- 定時内 OR 定時後 OR 休日？
- 可能な限り皆が参加できるのが好ましい（平日定時後が有力？）

**Comment by pengin01** [comment]
> 定時内 OR 定時後 OR 休日？

休日は無しかなぁ、と思っています。
暫くは定時内で、帰社的な扱いで行こうと思います。

**頻度は件は、すごく難しいと思います** 
参加者が慣れてくれば（0からアプリを作ることが普通な状態）は、「こんなの作ろう～」とか「このチュートリアル改造しよう」とかで行けると思います。

そうなるまでは、↓これくらいの粒度に落とし込む必要があるかと思います。
https://github.com/NwHub/mob-pro/commit/a01137a547dc16bee16199b43405e7cd081deebe

これがすごく時間がかかります。（サンプル作りながらリスト作っているけど、既に5時間は使っている。。。。）
準備の時間を考えると２～3ヶ月が現実的かも、なにか周期を早める、いいアイディアを募集します！

**Comment by miyazoon** [comment]
定時内だと参加者の業務進捗との兼ね合いが気になりますが、
そこはやってみないと何とも言えないですね。（定時後は負担が大きいので、定時内にやるのが理想）

確かに準備の負担がかなり大きいので、そこは持ち回りでやれれば良いかなと思いました。
（複数人で間隔をズラして準備できれば、周期を早めることもできそうかと）

**Comment by pengin01** [comment]
当日の進行スケジュール作ってみたら、とりあえず2日がかりになりそう。（短いスパンで2回はできる！）
https://github.com/NwHub/mob-pro/blob/main/%E7%AC%AC1%E5%9B%9E%E3%83%A2%E3%83%96%E3%83%97%E3%83%AD.md
